### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ApplicationUserSolution
name: "ApplicationUserSolution"
type: solution
metadata: 
  title: "Microsoft Dataverse ApplicationUserSolution Solution Reference | MicrosoftDocs"
  ms.date: "10/13/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 31ed80ab-8352-4195-9ab2-918d02770101
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "margoc"
  meta-description: "Reference information about the Microsoft Dataverse ApplicationUserSolution Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: ApplicationUserSolution
 version: "1.0.1.0"
 customization_prefix: default
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.applicationuser
     description: "Application User that has non-interactive access to the CDS system"
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Microsoft Dataverse Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex