### YamlMime:OData
uid: Microsoft.Dynamics.CRM.CRMSettingsAPIs
name: "Microsoft Dynamics 365 Settings APIs"
type: solution
metadata: 
  title: "Microsoft Dataverse Microsoft Dynamics 365 Settings APIs Solution Reference | MicrosoftDocs"
  ms.date: "10/13/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 9212dd81-410a-408b-8cc5-b6bc4d09d1b6
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "margoc"
  meta-description: "Reference information about the Microsoft Dataverse Microsoft Dynamics 365 Settings APIs Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: CRMSettingsAPIs
 version: "10.0.0.214"
 customization_prefix: msdyn
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.msdyn_solutioncomponentdatasource
     description: ""
   - type: Microsoft.Dynamics.CRM.msdyn_solutioncomponentsummary
     description: ""
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Microsoft Dataverse Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex