### YamlMime:OData
uid: Microsoft.Dynamics.CRM.EnvironmentVariables
name: "Environment Variables"
type: solution
metadata: 
  title: "Microsoft Dataverse Environment Variables Solution Reference | MicrosoftDocs"
  ms.date: "10/13/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 76103149-ae1d-4e2b-98c0-15c35f503ece
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "margoc"
  meta-description: "Reference information about the Microsoft Dataverse Environment Variables Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: EnvironmentVariables
 version: "1.0.2.77"
 customization_prefix: default
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.environmentvariabledefinition
     description: "Contains information about the settable variable: its type, default value, and etc."
   - type: Microsoft.Dynamics.CRM.environmentvariablevalue
     description: "Holds the value for the associated EnvironmentVariableDefinition entity."
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Microsoft Dataverse Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex