### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_teamsdialersettings
name: "Teams Dialer Settings"
type: solution
metadata: 
  title: "Microsoft Dataverse Teams Dialer Settings Solution Reference | MicrosoftDocs"
  ms.date: "04/12/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 870049d3-1f5d-48a4-9e0b-57e837a5bde2
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse Teams Dialer Settings Solution."
namespace: Microsoft.Dynamics.CRM
header:
 description: "Dynamics 365 workload for Teams Dialer Settings."
 unique_name: msdyn_teamsdialersettings
 version: "9.1.21031.1010"
 customization_prefix: msdyn
# This solution includes no entities.
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Microsoft Dataverse Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex