### YamlMime:OData
uid: Microsoft.Dynamics.CRM.applicationuser
name: "applicationuser"
type: entitytype
metadata: 
  title: "Microsoft Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "06/02/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 38d7a3db-99a3-415f-baf5-b15a59196f75
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse applicationuser entitytype."
description: "Application User that has non-interactive access to the CDS system"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/applicationusers"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: ApplicationUser
  primary_key: applicationuserid
  primary_name_attribute: applicationname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: applicationid
      type: Edm.Guid
      display_name: "applicationId"
      description: "Application Id"
      iscomputed: false
      isreadonly: false
    - name: applicationname
      type: Edm.String
      display_name: "Application name"
      description: "Application Name of the application user"
      iscomputed: false
      isreadonly: false
    - name: applicationtype
      type: Edm.Int32
      display_name: "ApplicationType"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "First party applications"
        - value: 1
          label: "Platform applications"
        - value: 2
          label: "External applications"
    - name: applicationuserid
      type: Edm.Guid
      display_name: "Application User"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: canimpersonateassystemuser
      type: Edm.Boolean
      display_name: "Can Impersonate As SystemUser"
      description: "Indicates whether the application user can impersonate system user"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Is Customizable"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the ApplicationUser"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the ApplicationUser"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _businessunitid_value
    single_valued_navigation_property:
    - businessunitid
    description: "Business Unit Id"
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: businessunitid
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_applicationuser
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_applicationuser_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_applicationuser_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_applicationuser_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_applicationuser_modifiedonbehalfby
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: applicationuser_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_applicationuser
  - name: applicationuser_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_applicationuser
  - name: applicationuser_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_applicationuser
  - name: applicationuser_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_applicationuser
  - name: applicationuser_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_applicationuser
  - name: applicationuser_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_applicationuser
  - name: applicationuser_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_applicationuser
  - name: applicationuser_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_applicationuser
  - name: applicationuserprofile
    type: Microsoft.Dynamics.CRM.fieldsecurityprofile
    partner: applicationuserprofile
  - name: applicationuserrole
    type: Microsoft.Dynamics.CRM.role
    partner: applicationuserrole
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the applicationuser entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the applicationuser entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.ApplicationUserSolution
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex